### ISSUE TITLE
[Suggestion] Add a cli

### ISSUE THREAD

**Issue by sbdchd** [vingorius/pug-beautify#1]
I am not sure if you had any places to create a command line interface for pug-beautify, but I think it would be a great feature.

**Comment by vingorius** [comment]
That's good idea. Is there a good example for reference ?

**Comment by sbdchd** [comment]
I think the [pug-cli](https://github.com/pugjs/pug-cli/blob/master/index.js) might be helpful.

**Comment by vingorius** [comment]
Tks @sbdchd , i'll try it.

**Comment by vingorius** [comment]
How to design the input/output ? overwrite the original file ? is it little bit dangerous? or just use STDOUT. how's your idea?

**Comment by sbdchd** [comment]
I think it would make sense to have it default to stdout and have an
optional flag to overwrite the original file.

**Comment by vingorius** [comment]
```
~$> pug-beautifier --help
usage: pug-beautify [options] file
option:-s, --fillspace <tab_size>,  fill <tab_size> spaces rather than tab, default tab.
option:-d, --omitdiv, omit div tag, default not.
option:-o,--overwrite, overwrite input file, default stdout.
```

That's psudo example.

**Comment by vingorius** [comment]
I open a new [repository](https://github.com/vingorius/pug-beautifier). and move #1 to there.

**Comment by vingorius** [comment]
Refer a new [repository](https://github.com/vingorius/pug-beautifier).
