### ISSUE TITLE
Can I use shift+ Alt +f in vscode?

### ISSUE THREAD

**Issue by tolerance-go** [vingorius/pug-beautify#5]
`editor.action.formatDocument`

**Comment by SergeShkurko** [comment]
@tolerance-go, perhaps you have confused the repository, this is the library used in [vs code pug beauty plugin](https://github.com/mrmlnc/vscode-pugbeautify).

**Comment by ducfilan** [comment]
@tolerance-go You can use this one: [this one](https://marketplace.visualstudio.com/items?itemName=ducfilan.pug-formatter)
